---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  config:
    envoy_prometheus_bind_addr: '0.0.0.0:9102'
    envoy_static_clusters_json: >
      {
        "connect_timeout": "3.000s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
          "cluster_name": "tempo_9411",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "tempo",
                        "port_value": 9411,
                        "protocol": "TCP"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "name": "tempo_9411",
        "type": "STRICT_DNS"
      }
    envoy_tracing_json: >
      {
        "http": {
          "name":"envoy.zipkin",
          "config":{
            "collector_cluster":"tempo",
            "collector_endpoint":"/api/v1/spans",
            "shared_span_context":false
          }
        }
      }
